### ISSUE TITLE
Import Carbon components

### ISSUE THREAD

**Issue by diego-codes** [ibm-frontend/gatsby-starter-carbon#6]
Once the Gatsby project has been created, Carbon React components and styles must be imported to be used in creating a Gatsby site.

This issue is complete when:
- [x] `carbon-components-react` is a dependency in this repo
- [x] Carbon's stylesheet are imported into the demo page
- [x] Importing Carbon React components is straight forward without having to dive deep into `node_modules` for import paths (Import path resolving)

**Comment by jlengstorf** [comment]
Styles are here: https://github.com/ibm-frontend/gatsby-starter-carbon/blob/master/src/layouts/index.scss#L13-L17

We should probably import the Carbon styles from the package, not unpkg.

**Comment by jlengstorf** [comment]
Each component imports the relevant MD components directly. We'll need to either drop examples (where irrelevant) or update to use Carbon.

https://github.com/ibm-frontend/gatsby-starter-carbon/blob/master/src/components/About/About.jsx#L2-L3
